### ISSUE TITLE
您好，是否可以关闭代理Ip

### ISSUE THREAD

**Issue by whnet** [KEN-LJQ/ZhihuSpyder#1]
运行后一直是代理ip 验证失败，偶尔有验证通过的，他也没有向数据库中存数据，请问这如何解决

**Comment by KEN-LJQ** [comment]
你好，现在暂时还不能关闭使用代理IP，这个我会在之后的提交中完善。然后对于你的问题可能的原因是：最近一个提交中代理IP已经不再存放到数据库中了，忘记了从sql文件中删除（很抱歉），所以数据库中会没有数据；其次是你需要将DBConnection 文件中的数据库配置改为你自己的（包括账号和密码）；最后是，程序的运行需要提供一个起始的用户token（例如：轮子哥的是excited-vczh），建议添加到数据库的user_list_cache表中。然后再试一试，等待获取到可用的代理后就会开始运行

**Comment by KEN-LJQ** [comment]
对于这个知乎爬虫的使用说明，我会尽快补充
