### ISSUE TITLE
关于爬虫代理模式的询问

### ISSUE THREAD

**Issue by LinuxBars** [KEN-LJQ/ZhihuSpyder#3]
环境：Cent0S 7 （Linux localhost.localdomain 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux）
按照文档修改数据库连接和添加用户 token 后
# 是否使用代理
IS_PROXY_ENABLE = False 时可以爬取数据
IS_PROXY_ENABLE = Ture  时创建的线程一直在等待连接

![screenshot from 2017-02-22 09-09-53](https://cloud.githubusercontent.com/assets/22124843/23192505/c2b4ac6c-f8de-11e6-979f-55e9d324176b.png)

非代理模式下爬取提示好像跟编码有关，我不清楚是哪里没有配置好：）
![screenshot from 2017-02-22 09-11-17](https://cloud.githubusercontent.com/assets/22124843/23192557/0b161c8e-f8df-11e6-8c40-61b8febe6475.png)

**Comment by KEN-LJQ** [comment]
代理是在程序运行后从国内的代理网站（使用的是西刺代理）上爬取下来并设置的，并不是内置的，由于这个代理网站是免费的可用的代理并不多。所以程序运行后会显示等待连接，其实已经在获取代理了，耐心等待几分钟就可以了。另外出现的异常可能跟数据库的编码有关，建议检查一下

**Comment by LinuxBars** [comment]
好的 非常感谢：）
